/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.Tads.TrabalhoFinalLTPII.Apresentation;

import br.edu.Tads.TrabalhoFinalLTPIII.DataAccess.CaixaDAO;
import br.edu.Tads.TrabalhoFinalLTPIII.DataAccess.MarcaDAO;
import br.edu.Tads.TrabalhoFinalLTPIII.DataAccess.SecaoDAO;
import br.edu.Tads.TrabalhoFinalLTPIII.DataAccess.UsuarioDAO;
import br.edu.Tads.TrabalhoFinalLTPIII.DomainModel.Caixa;
import br.edu.Tads.TrabalhoFinalLTPIII.DomainModel.Funcionario;
import br.edu.Tads.TrabalhoFinalLTPIII.DomainModel.Secao;
import br.edu.Tads.TrabalhoFinalLTPIII.DomainModel.Usuario;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jessica
 */
public class frmPrincipall extends javax.swing.JFrame {

    UsuarioDAO usuarioDAO = new UsuarioDAO();
    Usuario usuario;
    CaixaDAO caixaDAO = new CaixaDAO();
    Caixa caixa = new Caixa();
    Funcionario funcionario;
    Secao secao;
    SecaoDAO secaoDAO;
    MarcaDAO marcaDAO = new MarcaDAO();

    /**
     * Creates new form frmPrincipall
     *
     *
     *
     */
    public frmPrincipall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuLogoff = new javax.swing.JMenuItem();
        mnuCadastarCliente = new javax.swing.JMenu();
        mnuCadatrarClientes = new javax.swing.JMenuItem();
        mnuCadastarFornecedores = new javax.swing.JMenuItem();
        mnuCadastrarFuncionarios = new javax.swing.JMenuItem();
        mnuCargos = new javax.swing.JMenuItem();
        mnuAgendamento = new javax.swing.JMenuItem();
        mnuServico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuMarca = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sistema");

        jMenuItem4.setText("Sair");
        jMenu1.add(jMenuItem4);

        mnuLogoff.setText("Logof");
        mnuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoffActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogoff);

        jMenuBar1.add(jMenu1);

        mnuCadastarCliente.setText("Cadastros");

        mnuCadatrarClientes.setText("Cadastro de Clientes");
        mnuCadatrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadatrarClientesActionPerformed(evt);
            }
        });
        mnuCadastarCliente.add(mnuCadatrarClientes);

        mnuCadastarFornecedores.setText("Cadastro de Fornecedores");
        mnuCadastarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastarFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastarCliente.add(mnuCadastarFornecedores);

        mnuCadastrarFuncionarios.setText("Cadastro de Funcionarios");
        mnuCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarFuncionariosActionPerformed(evt);
            }
        });
        mnuCadastarCliente.add(mnuCadastrarFuncionarios);

        mnuCargos.setText("Cadastro de Cargos");
        mnuCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargosActionPerformed(evt);
            }
        });
        mnuCadastarCliente.add(mnuCargos);

        mnuAgendamento.setText("Agendamento");
        mnuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgendamentoActionPerformed(evt);
            }
        });
        mnuCadastarCliente.add(mnuAgendamento);

        mnuServico.setText("Servicos");
        mnuCadastarCliente.add(mnuServico);

        jMenuBar1.add(mnuCadastarCliente);

        jMenu2.setText("Produtos");

        jMenuItem1.setText("Cadastro de  Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        mnuMarca.setText("Cadastro de Marcas");
        mnuMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMarcaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMarca);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Caixa");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ferramentas");

        jMenuItem2.setText("Cadastro de Usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadatrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadatrarClientesActionPerformed
        frmClienteListagem janela = new frmClienteListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuCadatrarClientesActionPerformed

    private void mnuCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarFuncionariosActionPerformed
        frmFuncionarioListagem janela = new frmFuncionarioListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarFuncionariosActionPerformed

    private void mnuCadastarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastarFornecedoresActionPerformed
        frmFornecedorListagem janela = new frmFornecedorListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuCadastarFornecedoresActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmProdutoListagem janela = new frmProdutoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMarcaActionPerformed
        frmMarcaListagem janela;
        try {
            janela = new frmMarcaListagem();
        } catch (Exception ex) {
            Logger.getLogger(frmPrincipall.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuMarcaActionPerformed

    private void mnuCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargosActionPerformed
        frmCargoListagem janela = new frmCargoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuCargosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoffActionPerformed
       logoff();
    }//GEN-LAST:event_mnuLogoffActionPerformed

    private void mnuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgendamentoActionPerformed
        frmAgendamentoListagem janela = new frmAgendamentoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipall().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mnuAgendamento;
    private javax.swing.JMenu mnuCadastarCliente;
    private javax.swing.JMenuItem mnuCadastarFornecedores;
    private javax.swing.JMenuItem mnuCadastrarFuncionarios;
    private javax.swing.JMenuItem mnuCadatrarClientes;
    private javax.swing.JMenuItem mnuCargos;
    private javax.swing.JMenuItem mnuLogoff;
    private javax.swing.JMenuItem mnuMarca;
    private javax.swing.JMenuItem mnuServico;
    // End of variables declaration//GEN-END:variables

protected void logoff() {
        Date data = new Date();
        try {
            caixa = caixaDAO.AbrirCaixa(1);
            secao.setDataTermino(data);
            secao.setSaldoFechamento(caixa.getSaldo());
            secaoDAO.Salvar(secao);
            frmLogin janela = new frmLogin();

            janela.setVisible(true);
            setVisible(false);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }






}
