/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.Tads.TrabalhoFinal.Apresention;

/**
 *
 * @author Jessica
 */
public class frmClienteListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmClienteListagem
     */
    public frmClienteListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtClientebuscar = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnNovoCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        getContentPane().setLayout(null);
        getContentPane().add(txtClientebuscar);
        txtClientebuscar.setBounds(40, 20, 310, 30);

        btnBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        getContentPane().add(btnBuscarCliente);
        btnBuscarCliente.setBounds(370, 20, 80, 30);

        btnNovoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoCliente.setText("Novo");
        getContentPane().add(btnNovoCliente);
        btnNovoCliente.setBounds(460, 20, 80, 30);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENTES"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 500, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtClientebuscar;
    // End of variables declaration//GEN-END:variables
}
