/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.Tads.TrabalhoFinal.Apresention;


import br.edu.ifnmg.Tads.TrabalhoFinal.DomainModel.Email;
import br.edu.ifnmg.Tads.TrabalhoFinal.DomainModel.Endereco;
import java.awt.Component;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 
 */
/*public class frmEditarFuncionario extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form frmEditarFuncionario
     */
    /*public frmEditarFuncionario(int cod) {
        initComponents();
        funcionario = funcionariodao.Abrir(cod);
        pessoa = pessoadao.Abrir(funcionario.getCodpessoa());
        pessoa.setEmails(emaildao.Abrir(funcionario.getCodpessoa()));
        pessoa.setEnderecos(enderecodao.Abrir(funcionario.getCodpessoa()));
        pessoa.setTelefones(telefonedao.Abrir(funcionario.getCodpessoa()));
        carregadadospessoa();
        adicionaemailtable();
        adicionaenderecotable();
        adicionatelefonetable();
        
        lblcodigoendereco.setText(Integer.toString(0));
        lblcodigoemail.setText(Integer.toString(0));
        lblcodigotelefone.setText(Integer.toString(0));
        lblcodigoendereco.setVisible(false);
        lblcodigoemail.setVisible(false);
        lblcodigotelefone.setVisible(false);

    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdProfessor = new javax.swing.JTabbedPane();
        PanelDadosGerais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtDataNasc = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        PanelEndereco = new javax.swing.JPanel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnAdicionarEndereco = new javax.swing.JButton();
        btnRemoverEndereco = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblenderecos = new javax.swing.JTable();
        lblcodigoendereco = new javax.swing.JLabel();
        PanelTelefone = new javax.swing.JPanel();
        lblCodigoArea = new javax.swing.JLabel();
        lblNumeroTelefone = new javax.swing.JLabel();
        txtNumeroTelefone = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        btnAdicionarTelefone = new javax.swing.JButton();
        btnRemoverTelefone = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltelefone = new javax.swing.JTable();
        lblcodigotelefone = new javax.swing.JLabel();
        PanelEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRemoverEmail = new javax.swing.JButton();
        btnAdicionarEmail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemail = new javax.swing.JTable();
        lblcodigoemail = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Editar Funcinário");

        PanelDadosGerais.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        lblRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRg.setText("RG:");

        lblCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpf.setText("CPF:");

        lblDataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataNasc.setText("Nascimeto:");

        lblNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNivel.setText("Especialidade");

        javax.swing.GroupLayout PanelDadosGeraisLayout = new javax.swing.GroupLayout(PanelDadosGerais);
        PanelDadosGerais.setLayout(PanelDadosGeraisLayout);
        PanelDadosGeraisLayout.setHorizontalGroup(
            PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                                        .addComponent(txtRg)
                                        .addGap(39, 39, 39)
                                        .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNome)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDadosGeraisLayout.createSequentialGroup()
                                .addComponent(lblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addGap(422, 422, 422)))
                        .addGap(17, 17, 17))
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addComponent(lblNivel)
                        .addGap(18, 18, 18)
                        .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelDadosGeraisLayout.setVerticalGroup(
            PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );

        tbdProfessor.addTab("Dados Gerais", PanelDadosGerais);

        lblRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRua.setText("Rua:");

        lblNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumero.setText("Numero:");

        lblCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCidade.setText("Cidade:");

        lblBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBairro.setText("Bairro:");

        btnAdicionarEndereco.setBackground(new java.awt.Color(98, 155, 88));
        btnAdicionarEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_add.fw.png"))); // NOI18N
        btnAdicionarEndereco.setText("  Adicionar");
        btnAdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEnderecoActionPerformed(evt);
            }
        });

        btnRemoverEndereco.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverEndereco.setText("  Remover");
        btnRemoverEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEnderecoActionPerformed(evt);
            }
        });

        tblenderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Rua", "Numero", "Bairro", "Cidade"
            }
        ));
        tblenderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblenderecosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblenderecos);

        lblcodigoendereco.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigoendereco.setEnabled(false);

        javax.swing.GroupLayout PanelEnderecoLayout = new javax.swing.GroupLayout(PanelEndereco);
        PanelEndereco.setLayout(PanelEnderecoLayout);
        PanelEnderecoLayout.setHorizontalGroup(
            PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEnderecoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEnderecoLayout.createSequentialGroup()
                                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtRua)))
                                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(lblCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)
                                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionarEndereco)
                                    .addComponent(btnRemoverEndereco))
                                .addGap(289, 289, 289))))
                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                        .addComponent(lblcodigoendereco)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelEnderecoLayout.setVerticalGroup(
            PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btnRemoverEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(lblcodigoendereco))
                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(lblRua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        tbdProfessor.addTab("Endereco", PanelEndereco);

        lblCodigoArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigoArea.setText("DDD:");

        lblNumeroTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumeroTelefone.setText("Telefone:");

        btnAdicionarTelefone.setBackground(new java.awt.Color(98, 155, 88));
        btnAdicionarTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_add.fw.png"))); // NOI18N
        btnAdicionarTelefone.setText("Adicionar");
        btnAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTelefoneActionPerformed(evt);
            }
        });

        btnRemoverTelefone.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverTelefone.setText("Remover");
        btnRemoverTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTelefoneActionPerformed(evt);
            }
        });

        tbltelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "DDD", "Telefone"
            }
        ));
        tbltelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltelefoneMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbltelefone);

        javax.swing.GroupLayout PanelTelefoneLayout = new javax.swing.GroupLayout(PanelTelefone);
        PanelTelefone.setLayout(PanelTelefoneLayout);
        PanelTelefoneLayout.setHorizontalGroup(
            PanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTelefoneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelTelefoneLayout.createSequentialGroup()
                        .addComponent(lblCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTelefoneLayout.createSequentialGroup()
                                .addGap(365, 365, 365)
                                .addComponent(lblcodigotelefone))
                            .addGroup(PanelTelefoneLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblNumeroTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnAdicionarTelefone)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoverTelefone)))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        PanelTelefoneLayout.setVerticalGroup(
            PanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTelefoneLayout.createSequentialGroup()
                .addGroup(PanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTelefoneLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblcodigotelefone))
                    .addGroup(PanelTelefoneLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(PanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarTelefone)
                            .addComponent(btnRemoverTelefone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        tbdProfessor.addTab("Telefone", PanelTelefone);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("EMAIL:");

        btnRemoverEmail.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverEmail.setText("Remover");
        btnRemoverEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEmailActionPerformed(evt);
            }
        });

        btnAdicionarEmail.setBackground(new java.awt.Color(98, 155, 88));
        btnAdicionarEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_add.fw.png"))); // NOI18N
        btnAdicionarEmail.setText("Adicionar");
        btnAdicionarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEmailActionPerformed(evt);
            }
        });

        tblemail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Email"
            }
        ));
        tblemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblemailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblemail);

        javax.swing.GroupLayout PanelEmailLayout = new javax.swing.GroupLayout(PanelEmail);
        PanelEmail.setLayout(PanelEmailLayout);
        PanelEmailLayout.setHorizontalGroup(
            PanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmailLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEmailLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEmailLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnAdicionarEmail)
                                .addGap(30, 30, 30)
                                .addComponent(btnRemoverEmail)
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addGroup(PanelEmailLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblcodigoemail)
                                .addGap(148, 148, 148)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PanelEmailLayout.setVerticalGroup(
            PanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcodigoemail)
                .addGroup(PanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEmailLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEmailLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        tbdProfessor.addTab("Email", PanelEmail);

        btnAtualizar.setBackground(new java.awt.Color(98, 155, 88));
        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_confirm.fw.png"))); // NOI18N
        btnAtualizar.setText("Salvar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(183, 70, 53));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cancel.fw.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnAtualizar)
                        .addGap(63, 63, 63)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tbdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   /* private void carregadadospessoa(){
        txtNome.setText(pessoa.getNome());
        txtCpf.setText(Integer.toString(pessoa.getCpf()));
        txtRg.setText(pessoa.getRg());
        txtCargo.setText(funcionario.getCargo());
        txtSiape.setText(funcionario.getSiape());
    }
    
    private void adicionaemailtable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Emails");
        for (Email em : pessoa.getEmails()){
            Vector v = new Vector();
            v.add(em.getCodemail());
            v.add(em);
            model.addRow(v);
        }
        tblemail.setModel(model);
    }
    
    private void adicionaenderecotable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Rua");
        model.addColumn("Numero");
        model.addColumn("Complemento");
        model.addColumn("Bairro");
        model.addColumn("Cidade");
        for (Endereco en : pessoa.getEnderecos()){
            Vector v = new Vector();
            v.add(en.getCodendereco());
            v.add(en);
            v.add(en.getNumero());
            v.add(en.getComplemento());
            v.add(en.getBairro());
            v.add(en.getCidade());
            model.addRow(v);
        }
        
        tblenderecos.setModel(model);
    }
    
    private void adicionatelefonetable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Codigo Area");
        model.addColumn("Numero");
        for (Telefone tel : pessoa.getTelefones()){
            Vector v = new Vector();
            v.add(tel.getCodtelefone());
            v.add(tel.getDdd());
            v.add(tel);
            model.addRow(v);
        }
        
        tbltelefone.setModel(model);
    }                                    
    
    private void LimpaCamposEndereco(){
        lblcodigoendereco.setText(Integer.toString(0));
        txtRua.setText("");
        txtNumero.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCep.setText("");
        txtEstado.setText("");
        txtPais.setText("");
    }
    
    private void LimpaCamposEmail(){
        lblcodigoemail.setText(Integer.toString(0));
        txtEmail.setText("");
    }
    
    private void LimpaCamposTelefone(){
        lblcodigotelefone.setText(Integer.toString(0));
        txtArea.setText("");
        txtNumeroTelefone.setText("");
    }

    
    private void btnAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEnderecoActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja adicionar endereco?") == 0){
            int codendereco = Integer.parseInt(lblcodigoendereco.getText());
            Endereco enderecoanterior = null;
            if (codendereco > 0){
                for (Endereco end : pessoa.getEnderecos()){
                    if (end.getCodendereco() == codendereco){
                        enderecoanterior = end;
                    }
                }
                if (pessoa.getEnderecos().contains(enderecoanterior))
                pessoa.removeEnderecos(enderecoanterior);
            }

            Endereco endereco = new Endereco();

            if (codendereco > 0){
                endereco.setCodendereco(codendereco);
            }
            endereco.setRua(txtRua.getText());
            endereco.setNumero(Integer.parseInt(txtNumero.getText()));
            endereco.setComplemento(txtComplemento.getText());
            endereco.setBairro(txtBairro.getText());
            endereco.setCidade(txtCidade.getText());
            endereco.setEstado(txtEstado.getText());
            endereco.setCep(Integer.parseInt(txtCep.getText()));
            endereco.setPais(txtPais.getText());
            endereco.setPessoa(pessoa);

            if (pessoa.getEnderecos().contains(endereco)){
                JOptionPane.showMessageDialog(RootPane, "Endereço já adicionado!");
            } else {
                pessoa.addEnderecos(endereco);
                adicionaenderecotable();
                LimpaCamposEndereco();

                if (endereco.getCodendereco() == 0){
                    JOptionPane.showMessageDialog(RootPane, "Endereço adicionado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(RootPane, "Endereço alterado com sucesso!");
                }
            }
        }
    }//GEN-LAST:event_btnAdicionarEnderecoActionPerformed

    private void btnRemoverEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEnderecoActionPerformed
        // TODO add your handling code here:

        if (tblenderecos.getSelectedRow() >= 0){

            if (JOptionPane.showConfirmDialog(RootPane, "Deseja remover este endereço?") == 0){
                Endereco enderecoselect = (Endereco) tblenderecos.getValueAt(tblenderecos.getSelectedRow(), 1);

                if (pessoa.getEnderecos().contains(enderecoselect)){
                    pessoa.removeEnderecos(enderecoselect);
                    if (enderecoselect.getCodendereco() > 0){
                        enderecoapagar.add(enderecoselect);
                    }
                }

                JOptionPane.showMessageDialog(RootPane, "Endereço removido com sucesso!");
                adicionaenderecotable();
                LimpaCamposEndereco();
            } else {
                JOptionPane.showMessageDialog(RootPane, "Remoção cancelada!");
            }
        } else {
            JOptionPane.showMessageDialog(RootPane, "Selecione um endereço por favor!");
        }
    }//GEN-LAST:event_btnRemoverEnderecoActionPerformed

    private void tblenderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblenderecosMouseClicked
        // TODO add your handling code here:
        Endereco en = (Endereco) tblenderecos.getValueAt(tblenderecos.getSelectedRow(), 1);
        lblcodigoendereco.setText(Integer.toString(en.getCodendereco()));
        txtRua.setText(en.getRua());
        txtNumero.setText(Integer.toString(en.getNumero()));
        txtComplemento.setText(en.getComplemento());
        txtBairro.setText(en.getBairro());
        txtCidade.setText(en.getCidade());
        txtCep.setText(Integer.toString(en.getCep()));
        txtEstado.setText(en.getEstado());
        txtPais.setText(en.getPais());
    }//GEN-LAST:event_tblenderecosMouseClicked

    private void btnAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelefoneActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja adicionar telefone?") == 0){
            int codtelefone = Integer.parseInt(lblcodigotelefone.getText());
            Telefone telefoneanterior = null;

            if (codtelefone > 0){
                for(Telefone tel : pessoa.getTelefones()){
                    if (tel.getCodtelefone() == codtelefone){
                        telefoneanterior = tel;
                    }
                }

                if (pessoa.getTelefones().contains(telefoneanterior)){
                    pessoa.removeTelefones(telefoneanterior);
                }

            }

            Telefone telefone = new Telefone();

            if (codtelefone > 0){
                telefone.setCodtelefone(codtelefone);
            }

            telefone.setDdd(Integer.parseInt(txtArea.getText()));
            telefone.setNumero(Integer.parseInt(txtNumeroTelefone.getText()));
            telefone.setPessoa(pessoa);
            if(pessoa.getTelefones().contains(telefone)){
                JOptionPane.showMessageDialog(RootPane, "Telefone já adicionado!");
            } else {
                pessoa.addTelefones(telefone);
                adicionatelefonetable();
                LimpaCamposTelefone();

                if (telefone.getCodtelefone() == 0){
                    JOptionPane.showMessageDialog(RootPane, "Telefone adicionado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(RootPane, "Telefone alterado com sucesso!");
                }
            }
        }
    }//GEN-LAST:event_btnAdicionarTelefoneActionPerformed

    private void btnRemoverTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTelefoneActionPerformed
        // TODO add your handling code here:
        if (tbltelefone.getSelectedRow() >= 0){

            if (JOptionPane.showConfirmDialog(RootPane, "Deseja remover este telefone?") == 0){

                Telefone telefoneselect = (Telefone) tbltelefone.getValueAt(tbltelefone.getSelectedRow(), 2);

                if (pessoa.getTelefones().contains(telefoneselect)){
                    pessoa.removeTelefones(telefoneselect);
                    if (telefoneselect.getCodtelefone() > 0){
                        telefoneapagar.add(telefoneselect);
                    }
                }

                JOptionPane.showMessageDialog(RootPane, "Telefone removido com sucesso!");

                adicionatelefonetable();
                LimpaCamposTelefone();
            } else {
                JOptionPane.showMessageDialog(RootPane, "Remoção cancelada!");
            }
        } else {
            JOptionPane.showMessageDialog(RootPane, "Selecione um telefone por favor!");
        }
    }//GEN-LAST:event_btnRemoverTelefoneActionPerformed

    private void tbltelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltelefoneMouseClicked
        // TODO add your handling code here:
        Telefone tel = (Telefone) tbltelefone.getValueAt(tbltelefone.getSelectedRow(), 2);
        txtArea.setText(Integer.toString(tel.getDdd()));
        txtNumeroTelefone.setText(Integer.toString(tel.getNumero()));
    }//GEN-LAST:event_tbltelefoneMouseClicked

    private void btnRemoverEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEmailActionPerformed
        // TODO add your handling code here:

        if (tblemail.getSelectedRow() >= 0){

            if (JOptionPane.showConfirmDialog(RootPane, "Deseja remover este email?") == 0){
                Email emailselect = (Email) tblemail.getValueAt(tblemail.getSelectedRow(), 1);

                if (pessoa.getEmails().contains(emailselect)){
                    pessoa.removeEmails(emailselect);
                    if (emailselect.getCodemail() > 0){
                        emailapagar.add(emailselect);
                    }
                }

                JOptionPane.showMessageDialog(RootPane, "Email removido com sucesso!");

                adicionaemailtable();
                LimpaCamposEmail();
            } else {
                JOptionPane.showMessageDialog(RootPane, "Remoção cancelada!");
            }
        } else {
            JOptionPane.showMessageDialog(RootPane, "Selecione um email por favor!");
        }
    }//GEN-LAST:event_btnRemoverEmailActionPerformed

    private void btnAdicionarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEmailActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja adicionar email?") == 0){
            int codemail = Integer.parseInt(lblcodigoemail.getText());
            Email emailanterior = null;

            if (codemail > 0){
                for (Email em : pessoa.getEmails()){
                    if (em.getCodemail() == codemail){
                        emailanterior = em;
                    }
                }

                if (pessoa.getEmails().contains(emailanterior)){
                    pessoa.removeEmails(emailanterior);
                }
            }

            Email email = new Email();

            if (codemail > 0){
                email.setCodemail(codemail);
            }

            email.setEndereco(txtEmail.getText());
            email.setPessoa(pessoa);

            if (pessoa.getEmails().contains(email)){
                JOptionPane.showMessageDialog(RootPane, "Email já adicionado!");
            } else {
                pessoa.addEmails(email);
                adicionaemailtable();
                LimpaCamposEmail();
                if (email.getCodemail() == 0){
                    JOptionPane.showMessageDialog(RootPane, "Email adicionado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(RootPane, "Email alterado com sucesso!");
                }
            }

        }
    }//GEN-LAST:event_btnAdicionarEmailActionPerformed

    private void tblemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblemailMouseClicked
        // TODO add your handling code here:
        Email ema = (Email) tblemail.getValueAt(tblemail.getSelectedRow(), 1);
        txtEmail.setText(ema.getEndereco());
    }//GEN-LAST:event_tblemailMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja Atualizar o Funcionário?") == 0){
            pessoa.setNome(txtNome.getText());
            pessoa.setRg(txtRg.getText());
            pessoa.setCpf(Integer.parseInt(txtCpf.getText()));
            //pessoa.setDatanasc(datanasc);

            if (pessoadao.Salvar(pessoa)) {

                for(Email em : pessoa.getEmails()){
                    email = new Email(em.getCodemail(), em.getEndereco(), pessoa);
                    emaildao.Salvar(email);
                }

                for (Endereco en : pessoa.getEnderecos()){
                    endereco = new Endereco(en.getCodendereco(), en.getRua(), en.getNumero(), en.getComplemento(), en.getBairro(), en.getCidade(), en.getCep(), en.getEstado(), en.getPais(), pessoa);
                    enderecodao.Salvar(endereco);
                }

                for (Telefone tel : pessoa.getTelefones()){
                    telefone = new Telefone(tel.getCodtelefone(), tel.getDdd(), tel.getNumero(), pessoa);
                    telefonedao.Salvar(telefone);
                }

                for (Email emap : emailapagar){
                    emaildao.Apagar(emap.getCodemail());
                }

                for (Endereco enap : enderecoapagar){
                    enderecodao.Apagar(enap.getCodendereco());
                }

                for (Telefone telap : telefoneapagar){
                    telefonedao.Apagar(telap.getCodtelefone());
                }
                
                funcionario.setCargo(txtCargo.getText());
                funcionario.setSiape(txtSiape.getText());
                funcionario.setPessoa(pessoa);
                funcionariodao.Salvar(funcionario);

                JOptionPane.showMessageDialog(RootPane, "Funcionário Atualizado com Sucesso!");
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(RootPane, "Atualização Cancelada!");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja Cancelar a Atualização?") == 0){
            JOptionPane.showMessageDialog(RootPane, "Atualização Cancelada!");
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDadosGerais;
    private javax.swing.JPanel PanelEmail;
    private javax.swing.JPanel PanelEndereco;
    private javax.swing.JPanel PanelTelefone;
    private javax.swing.JButton btnAdicionarEmail;
    private javax.swing.JButton btnAdicionarEndereco;
    private javax.swing.JButton btnAdicionarTelefone;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemoverEmail;
    private javax.swing.JButton btnRemoverEndereco;
    private javax.swing.JButton btnRemoverTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigoArea;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroTelefone;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblcodigoemail;
    private javax.swing.JLabel lblcodigoendereco;
    private javax.swing.JLabel lblcodigotelefone;
    private javax.swing.JTabbedPane tbdProfessor;
    private javax.swing.JTable tblemail;
    private javax.swing.JTable tblenderecos;
    private javax.swing.JTable tbltelefone;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroTelefone;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}*/
